global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['192.168.50.104:9090']
      
  - job_name: 'prometheusApp'
    scrape_interval: 1s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['192.168.50.111:8031','192.168.50.111:8020','192.168.50.111:8021']
    #- job_name: 'grafana'
    #  static_configs:
     #   - targets: ['192.168.30.28:3000']

  # 采集MySQL监控数据
   # - job_name: 'mysqld_exporter'
    #  static_configs:
    #    - targets: ['192.168.30.28:9104']

  # 采集node exporter监控数据，即linux
   # - job_name: 'node-exporter'
    #  static_configs:
     #         - targets: ['192.168.30.28:9100']