name: Publish to Docker
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  packages: write
  contents: read
jobs:
  publish-prometheus-exporter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: registry.cn-shanghai.aliyuncs.com/liangtie/prometheus-exporter
          tags: latest

      - name: Login to aliyun
        uses: docker/login-action@v3
        with:
          registry: registry.cn-shanghai.aliyuncs.com
          username: Liangtie
          password: ${{ secrets.ALIYUNCS_DOCKER_PASSWORD }}
      - name: Build container
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}